name: Assembly_Dumper_Build

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]
   workflow_dispatch:
  

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout AssemblyDumper Repository
       uses: actions/checkout@v2
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Build
       run: dotnet build /p:Configuration=ReleaseLinux
       working-directory: ./AssemblyDumper.ConsoleApp/
     - name: Upload AssemblyDumper
       uses: actions/upload-artifact@v2
       with:
         name: AssemblyDumper
         path: /home/runner/work/AssetRipper/AssetRipper/AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/*
         if-no-files-found: error
      
    generate_old:
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Download AssemblyDumper
       uses: actions/download-artifact@v2
       with:
        name: AssemblyDumper
        path: ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/
     - name: Checkout TypeTreeDumps Repository
       uses: actions/checkout@v2
       with:
        repository: 'AssetRipper/TypeTreeDumps'
        path: TypeTreeDumps
     - name: Make files executable
       shell: bash
       run: |
        chmod +x ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/AssemblyDumper.ConsoleApp
        chmod +x ./generate_all.sh
        chmod +x ./get_names.sh
     - name: Run Generation
       shell: bash
       run: ./generate_all.sh 1
     - name: Upload Assemblies
       uses: actions/upload-artifact@v2
       with:
         name: Assemblies_Old
         path: /home/runner/work/AssetRipper/AssetRipper/Output/*
         if-no-files-found: error
      
    generate_2017:
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Download AssemblyDumper
       uses: actions/download-artifact@v2
       with:
        name: AssemblyDumper
        path: ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/
     - name: Checkout TypeTreeDumps Repository
       uses: actions/checkout@v2
       with:
        repository: 'AssetRipper/TypeTreeDumps'
        path: TypeTreeDumps
     - name: Make files executable
       shell: bash
       run: |
        chmod +x ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/AssemblyDumper.ConsoleApp
        chmod +x ./generate_all.sh
        chmod +x ./get_names.sh
     - name: Run Generation
       shell: bash
       run: ./generate_all.sh 2017
     - name: Upload Assemblies
       uses: actions/upload-artifact@v2
       with:
         name: Assemblies_2017
         path: /home/runner/work/AssetRipper/AssetRipper/Output/*
         if-no-files-found: error
      
    generate_2018:
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Download AssemblyDumper
       uses: actions/download-artifact@v2
       with:
        name: AssemblyDumper
        path: ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/
     - name: Checkout TypeTreeDumps Repository
       uses: actions/checkout@v2
       with:
        repository: 'AssetRipper/TypeTreeDumps'
        path: TypeTreeDumps
     - name: Make files executable
       shell: bash
       run: |
        chmod +x ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/AssemblyDumper.ConsoleApp
        chmod +x ./generate_all.sh
        chmod +x ./get_names.sh
     - name: Run Generation
       shell: bash
       run: ./generate_all.sh 2018
     - name: Upload Assemblies
       uses: actions/upload-artifact@v2
       with:
         name: Assemblies_2018
         path: /home/runner/work/AssetRipper/AssetRipper/Output/*
         if-no-files-found: error
      
    generate_2019:
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Download AssemblyDumper
       uses: actions/download-artifact@v2
       with:
        name: AssemblyDumper
        path: ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/
     - name: Checkout TypeTreeDumps Repository
       uses: actions/checkout@v2
       with:
        repository: 'AssetRipper/TypeTreeDumps'
        path: TypeTreeDumps
     - name: Make files executable
       shell: bash
       run: |
        chmod +x ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/AssemblyDumper.ConsoleApp
        chmod +x ./generate_all.sh
        chmod +x ./get_names.sh
     - name: Run Generation
       shell: bash
       run: ./generate_all.sh 2019
     - name: Upload Assemblies
       uses: actions/upload-artifact@v2
       with:
         name: Assemblies_2019
         path: /home/runner/work/AssetRipper/AssetRipper/Output/*
         if-no-files-found: error
      
    generate_2020:
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Download AssemblyDumper
       uses: actions/download-artifact@v2
       with:
        name: AssemblyDumper
        path: ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/
     - name: Checkout TypeTreeDumps Repository
       uses: actions/checkout@v2
       with:
        repository: 'AssetRipper/TypeTreeDumps'
        path: TypeTreeDumps
     - name: Make files executable
       shell: bash
       run: |
        chmod +x ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/AssemblyDumper.ConsoleApp
        chmod +x ./generate_all.sh
        chmod +x ./get_names.sh
     - name: Run Generation
       shell: bash
       run: ./generate_all.sh 2020
     - name: Upload Assemblies
       uses: actions/upload-artifact@v2
       with:
         name: Assemblies_2020
         path: /home/runner/work/AssetRipper/AssetRipper/Output/*
         if-no-files-found: error
      
    generate_2021:
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Download AssemblyDumper
       uses: actions/download-artifact@v2
       with:
        name: AssemblyDumper
        path: ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/
     - name: Checkout TypeTreeDumps Repository
       uses: actions/checkout@v2
       with:
        repository: 'AssetRipper/TypeTreeDumps'
        path: TypeTreeDumps
     - name: Make files executable
       shell: bash
       run: |
        chmod +x ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/AssemblyDumper.ConsoleApp
        chmod +x ./generate_all.sh
        chmod +x ./get_names.sh
     - name: Run Generation
       shell: bash
       run: ./generate_all.sh 2021
     - name: Upload Assemblies
       uses: actions/upload-artifact@v2
       with:
         name: Assemblies_2021
         path: /home/runner/work/AssetRipper/AssetRipper/Output/*
         if-no-files-found: error
      
    generate_2022:
     needs: build
     runs-on: ubuntu-latest
     steps:
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Download AssemblyDumper
       uses: actions/download-artifact@v2
       with:
        name: AssemblyDumper
        path: ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/
     - name: Checkout TypeTreeDumps Repository
       uses: actions/checkout@v2
       with:
        repository: 'AssetRipper/TypeTreeDumps'
        path: TypeTreeDumps
     - name: Make files executable
       shell: bash
       run: |
        chmod +x ./AssemblyDumper.ConsoleApp/bin/x64/ReleaseLinux/net6.0/AssemblyDumper.ConsoleApp
        chmod +x ./generate_all.sh
        chmod +x ./get_names.sh
     - name: Run Generation
       shell: bash
       run: ./generate_all.sh 2022
     - name: Upload Assemblies
       uses: actions/upload-artifact@v2
       with:
         name: Assemblies_2022
         path: /home/runner/work/AssetRipper/AssetRipper/Output/*
         if-no-files-found: error

    validate_and_upload:
     needs: [ generate_old, generate_2017, generate_2018, generate_2019, generate_2020, generate_2021, generate_2022 ]
     runs-on: ubuntu-latest
     steps:
     - name: Checkout AssemblyDumper Repository
       uses: actions/checkout@v2
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Build Validator
       run: dotnet build /p:Configuration=ReleaseLinux
       working-directory: ./AssemblyValidator/
     - name: Download Old Assemblies
       uses: actions/download-artifact@v2
       with:
        name: Assemblies_Old
        path: ./Output/
     - name: Download 2017 Assemblies
       uses: actions/download-artifact@v2
       with:
        name: Assemblies_2017
        path: ./Output/
     - name: Download 2018 Assemblies
       uses: actions/download-artifact@v2
       with:
        name: Assemblies_2018
        path: ./Output/
     - name: Download 2019 Assemblies
       uses: actions/download-artifact@v2
       with:
        name: Assemblies_2019
        path: ./Output/
     - name: Download 2020 Assemblies
       uses: actions/download-artifact@v2
       with:
        name: Assemblies_2020
        path: ./Output/
     - name: Download 2021 Assemblies
       uses: actions/download-artifact@v2
       with:
        name: Assemblies_2021
        path: ./Output/
     - name: Download 2022 Assemblies
       uses: actions/download-artifact@v2
       with:
        name: Assemblies_2022
        path: ./Output/
     - name: Run Validation
       shell: bash
       run: |
        chmod +x ./AssemblyValidator/bin/x64/ReleaseLinux/net6.0/AssemblyValidator
        ./AssemblyValidator/bin/x64/ReleaseLinux/net6.0/AssemblyValidator ./Output
     - name: Make Version List
       shell: bash
       run: |
        cd ./Output/
        ls > ../version_list.txt
        mv ../version_list.txt version_list.txt
        cd ..
     - name: Force Push Files To Branch
       if: ${{ github.event_name == 'push' && github.repository == 'AssetRipper/AssetRipper' }}
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: /home/runner/work/AssetRipper/AssetRipper/Output/
         publish_branch: assemblies
         force_orphan: true
         enable_jekyll: true