name: Auxiliary

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Build FileAnalyzer
      run: dotnet build /p:Configuration=Release
      working-directory: ./AssetRipper.Tools.FileAnalyzer/
        
    - name: Build FileExtractor
      run: dotnet build /p:Configuration=Release
      working-directory: ./AssetRipper.Tools.FileExtractor/
        
    - name: Build JsonSerializer
      run: dotnet build /p:Configuration=Release
      working-directory: ./AssetRipper.Tools.JsonSerializer/
      
    - name: Build SystemTester
      run: dotnet build /p:Configuration=Release
      working-directory: ./AssetRipper.Tools.SystemTester/
      
    - name: Build TypeTreeExtractor
      run: dotnet build /p:Configuration=Release
      working-directory: ./AssetRipper.Tools.TypeTreeExtractor/
      
    - name: Build Tests
      run: dotnet build /p:Configuration=Release
      working-directory: ./AssetRipper.Tests/
      
    - name: Run Tests
      run: dotnet test
      working-directory: ./AssetRipper.Tests/
