name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  publish_windows_x64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add Package Source
        run: dotnet nuget add source --name SamBoy "https://nuget.samboy.dev/v3/index.json"

      - name: Publish AssetRipper Windows x64
        run: dotnet publish /p:PublishProfile=windows_x64 /p:EnableCompressionInSingleFile=true /p:Configuration=Release
        working-directory: ./Source/AssetRipper.GUI/

      - name: List Files
        shell: bash
        run: |
          mkdir -p ./Source/0Bins/Publish/AssetRipper_win_x64/Licenses
          cp ./Source/Licenses/*.md ./Source/0Bins/Publish/AssetRipper_win_x64/Licenses/
          date -u > ./Source/0Bins/Publish/AssetRipper_win_x64/compile_time.txt
          ls -R ./Source/0Bins/Publish/AssetRipper_win_x64

      - name: Upload AssetRipper Windows x64
        uses: actions/upload-artifact@v3
        with:
          name: AssetRipper_win_x64
          path: ./Source/0Bins/Publish/AssetRipper_win_x64/*
          if-no-files-found: error

  publish_windows_arm64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add Package Source
        run: dotnet nuget add source --name SamBoy "https://nuget.samboy.dev/v3/index.json"

      - name: Publish AssetRipper Windows arm64
        run: dotnet publish /p:PublishProfile=windows_arm64 /p:EnableCompressionInSingleFile=true /p:Configuration=Release
        working-directory: ./Source/AssetRipper.GUI/

      - name: List Files
        shell: bash
        run: |
          mkdir -p ./Source/0Bins/Publish/AssetRipper_win_arm64/Licenses
          cp ./Source/Licenses/*.md ./Source/0Bins/Publish/AssetRipper_win_arm64/Licenses/
          date -u > ./Source/0Bins/Publish/AssetRipper_win_arm64/compile_time.txt
          ls -R ./Source/0Bins/Publish/AssetRipper_win_arm64

      - name: Upload AssetRipper Windows arm64
        uses: actions/upload-artifact@v3
        with:
          name: AssetRipper_win_arm64
          path: ./Source/0Bins/Publish/AssetRipper_win_arm64/*
          if-no-files-found: error

  publish_linux_x64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add Package Source
        run: dotnet nuget add source --name SamBoy "https://nuget.samboy.dev/v3/index.json"

      - name: Publish AssetRipper Linux x64
        run: dotnet publish /p:PublishProfile=linux_x64 /p:EnableCompressionInSingleFile=true /p:Configuration=Release
        working-directory: ./Source/AssetRipper.GUI/

      - name: List Files
        shell: bash
        run: |
          mkdir -p ./Source/0Bins/Publish/AssetRipper_linux_x64/Licenses
          cp ./Source/Licenses/*.md ./Source/0Bins/Publish/AssetRipper_linux_x64/Licenses/
          date -u > ./Source/0Bins/Publish/AssetRipper_linux_x64/compile_time.txt
          ls -R ./Source/0Bins/Publish/AssetRipper_linux_x64
          chmod +x ./Source/0Bins/Publish/AssetRipper_linux_x64/AssetRipper

      - name: Upload AssetRipper Linux x64
        uses: actions/upload-artifact@v3
        with:
          name: AssetRipper_linux_x64
          path: ./Source/0Bins/Publish/AssetRipper_linux_x64/*
          if-no-files-found: error

  publish_linux_arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add Package Source
        run: dotnet nuget add source --name SamBoy "https://nuget.samboy.dev/v3/index.json"

      - name: Publish AssetRipper Linux arm64
        run: dotnet publish /p:PublishProfile=linux_arm64 /p:EnableCompressionInSingleFile=true /p:Configuration=Release
        working-directory: ./Source/AssetRipper.GUI/

      - name: List Files
        shell: bash
        run: |
          mkdir -p ./Source/0Bins/Publish/AssetRipper_linux_arm64/Licenses
          cp ./Source/Licenses/*.md ./Source/0Bins/Publish/AssetRipper_linux_arm64/Licenses/
          date -u > ./Source/0Bins/Publish/AssetRipper_linux_arm64/compile_time.txt
          ls -R ./Source/0Bins/Publish/AssetRipper_linux_arm64
          chmod +x ./Source/0Bins/Publish/AssetRipper_linux_arm64/AssetRipper

      - name: Upload AssetRipper Linux arm64
        uses: actions/upload-artifact@v3
        with:
          name: AssetRipper_linux_arm64
          path: ./Source/0Bins/Publish/AssetRipper_linux_arm64/*
          if-no-files-found: error

  publish_mac_x64:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add Package Source
        run: dotnet nuget add source --name SamBoy "https://nuget.samboy.dev/v3/index.json"

      - name: Publish AssetRipper Mac x64
        run: dotnet publish /p:PublishProfile=mac_x64 /p:EnableCompressionInSingleFile=true /p:Configuration=Release
        working-directory: ./Source/AssetRipper.GUI/

      - name: List Files
        shell: bash
        run: |
          mkdir -p ./Source/0Bins/Publish/AssetRipper_mac_x64/Licenses
          cp ./Source/Licenses/*.md ./Source/0Bins/Publish/AssetRipper_mac_x64/Licenses/
          date -u > ./Source/0Bins/Publish/AssetRipper_mac_x64/compile_time.txt
          ls -R ./Source/0Bins/Publish/AssetRipper_mac_x64
          chmod +x ./Source/0Bins/Publish/AssetRipper_mac_x64/AssetRipper
          mkdir -p upload/AssetRipper.app/Contents/MacOS
          mkdir -p upload/AssetRipper.app/Contents/Resources
          cp -r Source/0Bins/Publish/AssetRipper_mac_x64/* upload/AssetRipper.app/Contents/MacOS/

          logo=Media/Images/LogoReimagined/LogoReimaginedTransparent.png
          mkdir AssetRipper.iconset
          sips -z 16 16     $logo --out AssetRipper.iconset/icon_16x16.png
          sips -z 32 32     $logo --out AssetRipper.iconset/icon_16x16@2x.png
          sips -z 32 32     $logo --out AssetRipper.iconset/icon_32x32.png
          sips -z 64 64     $logo --out AssetRipper.iconset/icon_32x32@2x.png
          sips -z 128 128   $logo --out AssetRipper.iconset/icon_128x128.png
          sips -z 256 256   $logo --out AssetRipper.iconset/icon_128x128@2x.png
          sips -z 256 256   $logo --out AssetRipper.iconset/icon_256x256.png
          sips -z 512 512   $logo --out AssetRipper.iconset/icon_256x256@2x.png
          sips -z 512 512   $logo --out AssetRipper.iconset/icon_512x512.png
          sips -z 1024 1024 $logo --out AssetRipper.iconset/icon_512x512@2x.png
          iconutil -c icns AssetRipper.iconset
          mv AssetRipper.icns upload/AssetRipper.app/Contents/Resources/

          version=$(cat Source/Directory.Build.props | sed -n 's:.*<Version>\(.*\)</Version>.*:\1:p')

          cat << EOF > upload/AssetRipper.app/Contents/Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
              <dict>
                  <key>CFBundleName</key>               <string>AssetRipper</string>
                  <key>CFBundleExecutable</key>         <string>AssetRipper</string>
                  <key>CFBundleIdentifier</key>         <string>assetripper</string>
                  <key>CFBundleIconFile</key>           <string>AssetRipper.icns</string>
                  <key>CFBundleVersion</key>            <string>$version</string>
                  <key>CFBundleShortVersionString</key> <string>$version</string>
                  <key>NSHighResolutionCapable</key>    <string>True</string>
              </dict>
          </plist>
          EOF

      - name: Upload AssetRipper Mac x64
        uses: actions/upload-artifact@v3
        with:
          name: AssetRipper_mac_x64
          path: ./upload/
          if-no-files-found: error

  publish_mac_arm64:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add Package Source
        run: dotnet nuget add source --name SamBoy "https://nuget.samboy.dev/v3/index.json"

      - name: Publish AssetRipper Mac arm64
        run: dotnet publish /p:PublishProfile=mac_arm64 /p:Configuration=Release
        working-directory: ./Source/AssetRipper.GUI/

      - name: List Files
        shell: bash
        run: |
          mkdir -p ./Source/0Bins/Publish/AssetRipper_mac_arm64/Licenses
          cp ./Source/Licenses/*.md ./Source/0Bins/Publish/AssetRipper_mac_arm64/Licenses/
          date -u > ./Source/0Bins/Publish/AssetRipper_mac_arm64/compile_time.txt
          ls -R ./Source/0Bins/Publish/AssetRipper_mac_arm64
          chmod +x ./Source/0Bins/Publish/AssetRipper_mac_arm64/AssetRipper
          mkdir -p upload/AssetRipper.app/Contents/MacOS
          mkdir -p upload/AssetRipper.app/Contents/Resources
          cp -r Source/0Bins/Publish/AssetRipper_mac_arm64/* upload/AssetRipper.app/Contents/MacOS/

          logo=Media/Images/LogoReimagined/LogoReimaginedTransparent.png
          mkdir AssetRipper.iconset
          sips -z 16 16     $logo --out AssetRipper.iconset/icon_16x16.png
          sips -z 32 32     $logo --out AssetRipper.iconset/icon_16x16@2x.png
          sips -z 32 32     $logo --out AssetRipper.iconset/icon_32x32.png
          sips -z 64 64     $logo --out AssetRipper.iconset/icon_32x32@2x.png
          sips -z 128 128   $logo --out AssetRipper.iconset/icon_128x128.png
          sips -z 256 256   $logo --out AssetRipper.iconset/icon_128x128@2x.png
          sips -z 256 256   $logo --out AssetRipper.iconset/icon_256x256.png
          sips -z 512 512   $logo --out AssetRipper.iconset/icon_256x256@2x.png
          sips -z 512 512   $logo --out AssetRipper.iconset/icon_512x512.png
          sips -z 1024 1024 $logo --out AssetRipper.iconset/icon_512x512@2x.png
          iconutil -c icns AssetRipper.iconset
          mv AssetRipper.icns upload/AssetRipper.app/Contents/Resources/

          version=$(cat Source/Directory.Build.props | sed -n 's:.*<Version>\(.*\)</Version>.*:\1:p')

          cat << EOF > upload/AssetRipper.app/Contents/Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
              <dict>
                  <key>CFBundleName</key>               <string>AssetRipper</string>
                  <key>CFBundleExecutable</key>         <string>AssetRipper</string>
                  <key>CFBundleIdentifier</key>         <string>assetripper</string>
                  <key>CFBundleIconFile</key>           <string>AssetRipper.icns</string>
                  <key>CFBundleVersion</key>            <string>$version</string>
                  <key>CFBundleShortVersionString</key> <string>$version</string>
                  <key>NSHighResolutionCapable</key>    <string>True</string>
              </dict>
          </plist>
          EOF

      - name: Upload AssetRipper Mac arm64
        uses: actions/upload-artifact@v3
        with:
          name: AssetRipper_mac_arm64
          path: ./upload/
          if-no-files-found: error
